# Generated by Django 5.2.3 on 2025-08-09 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farmer_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farmer_gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farmer_nin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farmer_phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farmer_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='recommender_nin',
            field=models.CharField(max_length=20),
        ),
    ]
