# Generated by Django 5.2.3 on 2025-08-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_farmer_user_alter_farmer_farmer_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='farmer_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farmer_type',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Returner', 'Returner')], max_length=50),
        ),
    ]
