# Generated by Django 5.2.3 on 2025-08-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_farmer_farmer_gender_alter_farmer_farmer_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
