# Generated by Django 5.2.3 on 2025-08-09 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_userprofile_options_alter_userprofile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickrequest',
            name='sales_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
