# Generated by Django 5.2.3 on 2025-08-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_chickrequest_sales_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
